apiVersion: v1
kind: Pod
metadata:
  name: spdk
spec:
  containers:
  - name: spdk-container
    image: evalsocket/spdk:v3
    volumeMounts:
    - name: dev-hostpath
      mountPath: /host/dev
      readOnly: true
    ports:
    - containerPort: 9009
    - containerPort: 4444
    - containerPort: 5555
    securityContext:
      privileged: true
    resources:
      limits:
        hugepages-1Gi: 1Gi
      requests:
        memory: 100Mi
  volumes:
  - name: dev-hostpath
    hostPath:
      path: /dev