apiVersion: v1
kind: Pod
metadata:
  name: spdk
spec:
  containers:
  - name: spdk
    image: evalsocket/spdk:latest
    ports:
    - containerPort: 9009
    - containerPort: 4444
    - containerPort: 5555
    securityContext:
      privileged: true
    resources:
      limits:
        hugepages-1Gi: 1Gi
      requests:
        memory: 100Mi
